services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      # bind port 80 to 8000 on the host machine
      - '8000:80'
    volumes:
      # bind the local src (our laravel app) directory to the container's /var/www/html directory
      - ./src:/var/www/html
      # pass in our own configuration by binding to the local path
      # set as read only with :ro, the container should not change the file
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # :delegated helps with performace by batching data written back to the host machine
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "/var/www/html/artisan" ]
  npm:
    image: node:14
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "npm" ]

volumes:
  mysql_data:
